import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Navbar from "@/components/navbar";
import { createClient } from "@/utils/serverclient";
import { Database } from "@/Types/database.types";
import { SupabaseClient } from "@supabase/supabase-js";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const supabase: SupabaseClient<Database> = await createClient();
  const { data: { session } } = await supabase.auth.getSession();

  console.log("User in RootLayout:", session?.user);

  

  

  

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar user={session?.user!}></Navbar>
        <div className="h-[2vh]"></div>
        {children}
      </body>
    </html>
  );
}
